import js from '@eslint/js';
import ts from 'typescript-eslint';

export default ts.config(
  { ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      'book/**',
      '**/*.js',
      // Generated by next build, and it is not ours to style.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          // Config files and the bun test file sit outside every tsconfig project.
          allowDefaultProject: [
            '*.mjs',
            'apps/web/*.mjs',
            'scripts/*.mjs',
            'packages/shared/src/*.test.ts',
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      // Prisma Decimal and Nest DI make these two noisy without catching bugs.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },
  {
    // Node scripts, not part of any app bundle.
    files: ['**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        fetch: 'readonly',
        Intl: 'readonly',
        URL: 'readonly',
      },
    },
  },
);
