'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ROLE_KEYS } from '@bobs-momo/shared';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select } from '@/components/ui/select';
import { PageHeader } from '@/components/ui/page-header';
import { errorMessage } from '@/features/analytics/report-frame';
import {
  adminKeys,
  createUser,
  listEmployees,
  listOutlets,
  type ProvisionedCredential,
} from '@/features/admin/api';
import { CredentialOnce } from '@/features/admin/credential-once';

export default function CreateUserPage() {
  const queryClient = useQueryClient();
  const [username, setUsername] = useState('');
  const [roleKey, setRoleKey] = useState<string>('KITCHEN_STAFF');
  const [employeeId, setEmployeeId] = useState('');
  const [outletIds, setOutletIds] = useState<string[]>([]);
  const [clientError, setClientError] = useState<string | null>(null);
  const [credential, setCredential] = useState<ProvisionedCredential | null>(null);

  const outlets = useQuery({
    queryKey: adminKeys.outlets(),
    queryFn: listOutlets,
    staleTime: 5 * 60 * 1000,
    retry: false,
  });

  const employees = useQuery({
    queryKey: adminKeys.employees(),
    queryFn: listEmployees,
    staleTime: 5 * 60 * 1000,
    retry: false,
  });

  const create = useMutation({
    mutationFn: () =>
      createUser({
        username: username.trim(),
        roleKey,
        employeeId: employeeId === '' ? null : employeeId,
        outletIds,
      }),
    onSuccess: (result) => {
      setCredential(result);
      setUsername('');
      setEmployeeId('');
      setOutletIds([]);
      void queryClient.invalidateQueries({ queryKey: adminKeys.all() });
    },
  });

  function submit(event: React.FormEvent) {
    event.preventDefault();
    setClientError(null);
    if (username.trim().length < 3) {
      setClientError('The username needs at least three characters.');
      return;
    }
    if (outletIds.length === 0) {
      setClientError('Pick at least one outlet. Outlet membership is what scopes everything the user sees.');
      return;
    }
    create.mutate();
  }

  return (
    <div className="space-y-4 pb-8">
      <PageHeader
        title="Create user"
        description="The password is generated by the server and shown once"
      />

      {credential ? (
        <CredentialOnce credential={credential} onDone={() => setCredential(null)} />
      ) : null}

      <form onSubmit={submit} noValidate className="space-y-4">
        <Card className="space-y-3 p-3">
          <div>
            <Label htmlFor="username">Username</Label>
            <Input
              id="username"
              className="min-h-[44px]"
              autoComplete="off"
              placeholder="raju.m"
              value={username}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setUsername(e.target.value)}
            />
            <p className="mt-1 text-xs text-text-muted">
              Staff type this on a phone keypad, so keep it short and lower case.
            </p>
          </div>

          <div>
            <Label htmlFor="role">Role</Label>
            <Select
              id="role"
              value={roleKey}
              onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setRoleKey(e.target.value)}
            >
              {ROLE_KEYS.map((key) => (
                <option key={key} value={key}>
                  {key.toLowerCase().replaceAll('_', ' ')}
                </option>
              ))}
            </Select>
          </div>

          <div>
            <Label htmlFor="employee">Employee</Label>
            <Select
              id="employee"
              value={employeeId}
              onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setEmployeeId(e.target.value)}
            >
              <option value="">No employee record</option>
              {(employees.data?.data ?? []).map((employee) => (
                <option key={employee.id} value={employee.id}>
                  {employee.employeeCode} {employee.fullName}
                </option>
              ))}
            </Select>
            <p className="mt-1 text-xs text-text-muted">
              Linking an employee is what lets this login punch in and be assigned tasks.
            </p>
          </div>
        </Card>

        <Card className="p-3">
          <fieldset>
            <legend className="text-sm font-semibold text-text">Outlets</legend>
            <p className="mt-1 text-xs text-text-muted">
              Everything this user can read is filtered by these outlets.
            </p>
            <div className="mt-2 space-y-2">
              {(outlets.data?.data ?? []).map((outlet) => (
                <Checkbox
                  key={outlet.id}
                  id={`outlet-${outlet.id}`}
                  checked={outletIds.includes(outlet.id)}
                  label={`${outlet.code} ${outlet.name}`}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                    setOutletIds((prev) =>
                      e.target.checked
                        ? [...prev, outlet.id]
                        : prev.filter((id) => id !== outlet.id),
                    )
                  }
                />
              ))}
              {(outlets.data?.data ?? []).length === 0 ? (
                <p className="text-sm text-text-muted">
                  No outlets loaded. Create an outlet first on the outlets screen.
                </p>
              ) : null}
            </div>
          </fieldset>
        </Card>

        {clientError ? (
          <p role="alert" className="rounded-md bg-danger-bg p-3 text-sm text-danger">
            {clientError}
          </p>
        ) : null}

        {create.isError ? (
          <p role="alert" className="rounded-md bg-danger-bg p-3 text-sm text-danger">
            {errorMessage(create.error)}
          </p>
        ) : null}

        <div className="flex flex-wrap gap-2">
          <Button type="submit" className="min-h-[44px]" disabled={create.isPending}>
            {create.isPending ? 'Creating' : 'Create user'}
          </Button>
          <Link href="/admin/users">
            <Button type="button" variant="secondary" className="min-h-[44px]">
              Back to users
            </Button>
          </Link>
        </div>
      </form>
    </div>
  );
}
