// The error envelope every non-2xx response uses. Chapter 15.
export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: unknown;
    requestId: string;
  };
}

// Append only, grouped by module prefix. Never reorder: it makes merges ugly.
export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REUSED: 'AUTH_TOKEN_REUSED',
  AUTH_PASSWORD_RESET_REQUIRED: 'AUTH_PASSWORD_RESET_REQUIRED',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_PERMISSIONS_STALE: 'AUTH_PERMISSIONS_STALE',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_SAME_PASSWORD: 'AUTH_SAME_PASSWORD',
  COMMON_VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_RATE_LIMITED: 'COMMON_RATE_LIMITED',
  COMMON_INTERNAL: 'COMMON_INTERNAL',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REPLAYED: 'IDEMPOTENCY_KEY_REPLAYED',
  INVENTORY_NEGATIVE_STOCK_BLOCKED: 'INVENTORY_NEGATIVE_STOCK_BLOCKED',
  INVENTORY_ITEM_NOT_FOUND: 'INVENTORY_ITEM_NOT_FOUND',
  INVENTORY_ITEM_INACTIVE: 'INVENTORY_ITEM_INACTIVE',
  INVENTORY_FUTURE_BUSINESS_DATE: 'INVENTORY_FUTURE_BUSINESS_DATE',
  INVENTORY_BACKDATE_LIMIT_EXCEEDED: 'INVENTORY_BACKDATE_LIMIT_EXCEEDED',
  INVENTORY_OPENING_ALREADY_RECORDED: 'INVENTORY_OPENING_ALREADY_RECORDED',
  INVENTORY_UNIT_LOCKED_BY_LEDGER: 'INVENTORY_UNIT_LOCKED_BY_LEDGER',
  VENDOR_NOT_FOUND: 'VENDOR_NOT_FOUND',
  VENDOR_NAME_TAKEN: 'VENDOR_NAME_TAKEN',
  VENDOR_INACTIVE: 'VENDOR_INACTIVE',
  PR_NOT_FOUND: 'PR_NOT_FOUND',
  PR_INVALID_TRANSITION: 'PR_INVALID_TRANSITION',
  PR_NEEDED_BY_IN_PAST: 'PR_NEEDED_BY_IN_PAST',
  PURCHASE_NOT_FOUND: 'PURCHASE_NOT_FOUND',
  PURCHASE_ALREADY_VOIDED: 'PURCHASE_ALREADY_VOIDED',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_ALREADY_EXITED: 'EMPLOYEE_ALREADY_EXITED',
  EMPLOYEE_USER_ALREADY_LINKED: 'EMPLOYEE_USER_ALREADY_LINKED',
  ATTENDANCE_ALREADY_PUNCHED_IN: 'ATTENDANCE_ALREADY_PUNCHED_IN',
  ATTENDANCE_NOT_PUNCHED_IN: 'ATTENDANCE_NOT_PUNCHED_IN',
  ATTENDANCE_BREAK_ALREADY_OPEN: 'ATTENDANCE_BREAK_ALREADY_OPEN',
  ATTENDANCE_BREAK_NOT_OPEN: 'ATTENDANCE_BREAK_NOT_OPEN',
  ATTENDANCE_PUNCH_NOT_FOUND: 'ATTENDANCE_PUNCH_NOT_FOUND',
  SHIFT_OVERLAP: 'SHIFT_OVERLAP',
  SHIFT_NOT_FOUND: 'SHIFT_NOT_FOUND',
  SHIFT_INVALID_RANGE: 'SHIFT_INVALID_RANGE',
  LEAVE_NOT_FOUND: 'LEAVE_NOT_FOUND',
  LEAVE_PAST_DATE: 'LEAVE_PAST_DATE',
  LEAVE_OVERLAP: 'LEAVE_OVERLAP',
  LEAVE_WINDOW_EXCEEDED: 'LEAVE_WINDOW_EXCEEDED',
  LEAVE_NOT_PENDING: 'LEAVE_NOT_PENDING',
  LEAVE_ALREADY_STARTED: 'LEAVE_ALREADY_STARTED',
  SALARY_PERIOD_OVERLAP: 'SALARY_PERIOD_OVERLAP',
  INVENTORY_REASON_REQUIRED: 'INVENTORY_REASON_REQUIRED',
  INVENTORY_UNIT_LOCKED: 'INVENTORY_UNIT_LOCKED',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
