// The error envelope every non-2xx response uses. Chapter 15.
export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: unknown;
    requestId: string;
  };
}

// Append only, grouped by module prefix. Never reorder: it makes merges ugly.
export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REUSED: 'AUTH_TOKEN_REUSED',
  AUTH_PASSWORD_RESET_REQUIRED: 'AUTH_PASSWORD_RESET_REQUIRED',
  COMMON_VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_RATE_LIMITED: 'COMMON_RATE_LIMITED',
  COMMON_INTERNAL: 'COMMON_INTERNAL',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REPLAYED: 'IDEMPOTENCY_KEY_REPLAYED',
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_REASON_REQUIRED: 'INVENTORY_REASON_REQUIRED',
  INVENTORY_UNIT_LOCKED: 'INVENTORY_UNIT_LOCKED',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
