// GENERATED from book/src/14-rbac-and-permissions.md.
// Regenerate with `bun run scripts/gen-permissions.mjs`. Do not hand edit.
// Scope modifiers: A = ALL_OUTLETS, O = OWN_OUTLET, S = SELF.

export type ScopeModifier = 'A' | 'O' | 'S';

export const PERMISSION_KEYS = [
  'auth.session.create',
  'auth.password.change',
  'auth.password.reset_other',
  'admin.user.create',
  'admin.user.read',
  'admin.user.update',
  'admin.user.disable',
  'admin.user.assign_role',
  'admin.user.assign_outlet',
  'admin.audit.read',
  'admin.outlet.manage',
  'admin.department.manage',
  'inventory.item.create',
  'inventory.item.read',
  'inventory.item.update',
  'inventory.item.deactivate',
  'inventory.category.manage',
  'inventory.unit.manage',
  'inventory.stock.read',
  'inventory.transaction.create',
  'inventory.transaction.read',
  'inventory.wastage.create',
  'inventory.adjustment.create',
  'inventory.transfer.create',
  'inventory.reorder_level.update',
  'purchase.request.create',
  'purchase.request.read',
  'purchase.request.approve',
  'purchase.request.cancel',
  'purchase.record.create',
  'purchase.record.read',
  'purchase.record.void',
  'purchase.price_history.read',
  'vendor.vendor.create',
  'vendor.vendor.read',
  'vendor.vendor.update',
  'vendor.vendor.deactivate',
  'workforce.employee.create',
  'workforce.employee.read',
  'workforce.employee.update',
  'workforce.attendance.punch_self',
  'workforce.attendance.read',
  'workforce.attendance.edit',
  'workforce.break.log_self',
  'workforce.shift.create',
  'workforce.shift.read',
  'workforce.leave.request',
  'workforce.leave.read',
  'workforce.leave.decide',
  'workforce.salary.read',
  'workforce.salary.write',
  'workforce.performance.read',
  'task.task.create',
  'task.task.read',
  'task.task.update_self',
  'task.task.complete',
  'task.task.verify',
  'task.task.cancel',
  'task.template.manage',
  'task.recurrence.manage',
  'task.comment.create',
  'sales.entry.create',
  'sales.entry.read',
  'sales.entry.amend',
  'sales.entry.unlock',
  'analytics.dashboard.read',
  'analytics.sales.read',
  'analytics.consumption.read',
  'analytics.performance.read',
  'analytics.waste.read',
  'analytics.pnl.read',
  'analytics.export.create',
  'messaging.direct.send',
  'messaging.broadcast.send',
  'messaging.message.read',
  'notification.own.read',
  'notification.preference.update',
  'crm.customer.read',
  'crm.game.configure',
  'crm.game.publish',
  'crm.reward.define',
  'crm.reward.issue',
  'crm.reward.redeem',
  'crm.analytics.read',
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const PERMISSIONS: Record<string, Partial<Record<PermissionKey, ScopeModifier>>> = {
  OWNER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'auth.password.reset_other': 'A',
    'admin.user.create': 'A',
    'admin.user.read': 'A',
    'admin.user.update': 'A',
    'admin.user.disable': 'A',
    'admin.user.assign_role': 'A',
    'admin.user.assign_outlet': 'A',
    'admin.audit.read': 'A',
    'admin.outlet.manage': 'A',
    'admin.department.manage': 'A',
    'inventory.item.create': 'A',
    'inventory.item.read': 'A',
    'inventory.item.update': 'A',
    'inventory.item.deactivate': 'A',
    'inventory.category.manage': 'A',
    'inventory.unit.manage': 'A',
    'inventory.stock.read': 'A',
    'inventory.transaction.create': 'A',
    'inventory.transaction.read': 'A',
    'inventory.wastage.create': 'A',
    'inventory.adjustment.create': 'A',
    'inventory.transfer.create': 'A',
    'inventory.reorder_level.update': 'A',
    'purchase.request.create': 'A',
    'purchase.request.read': 'A',
    'purchase.request.approve': 'A',
    'purchase.request.cancel': 'A',
    'purchase.record.create': 'A',
    'purchase.record.read': 'A',
    'purchase.record.void': 'A',
    'purchase.price_history.read': 'A',
    'vendor.vendor.create': 'A',
    'vendor.vendor.read': 'A',
    'vendor.vendor.update': 'A',
    'vendor.vendor.deactivate': 'A',
    'workforce.employee.create': 'A',
    'workforce.employee.read': 'A',
    'workforce.employee.update': 'A',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'A',
    'workforce.attendance.edit': 'A',
    'workforce.break.log_self': 'S',
    'workforce.shift.create': 'A',
    'workforce.shift.read': 'A',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'A',
    'workforce.leave.decide': 'A',
    'workforce.salary.read': 'A',
    'workforce.salary.write': 'A',
    'workforce.performance.read': 'A',
    'task.task.create': 'A',
    'task.task.read': 'A',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.task.verify': 'A',
    'task.task.cancel': 'A',
    'task.template.manage': 'A',
    'task.recurrence.manage': 'A',
    'task.comment.create': 'S',
    'sales.entry.create': 'A',
    'sales.entry.read': 'A',
    'sales.entry.amend': 'A',
    'sales.entry.unlock': 'A',
    'analytics.dashboard.read': 'A',
    'analytics.sales.read': 'A',
    'analytics.consumption.read': 'A',
    'analytics.performance.read': 'A',
    'analytics.waste.read': 'A',
    'analytics.pnl.read': 'A',
    'analytics.export.create': 'A',
    'messaging.direct.send': 'A',
    'messaging.broadcast.send': 'A',
    'messaging.message.read': 'A',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
    'crm.customer.read': 'A',
    'crm.game.configure': 'A',
    'crm.game.publish': 'A',
    'crm.reward.define': 'A',
    'crm.reward.issue': 'A',
    'crm.reward.redeem': 'A',
    'crm.analytics.read': 'A',
  },
  OPERATIONS_MANAGER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'auth.password.reset_other': 'A',
    'admin.user.read': 'A',
    'admin.user.assign_outlet': 'A',
    'admin.audit.read': 'A',
    'admin.department.manage': 'A',
    'inventory.item.create': 'A',
    'inventory.item.read': 'A',
    'inventory.item.update': 'A',
    'inventory.category.manage': 'A',
    'inventory.stock.read': 'A',
    'inventory.transaction.create': 'A',
    'inventory.transaction.read': 'A',
    'inventory.wastage.create': 'A',
    'inventory.adjustment.create': 'A',
    'inventory.transfer.create': 'A',
    'inventory.reorder_level.update': 'A',
    'purchase.request.create': 'A',
    'purchase.request.read': 'A',
    'purchase.request.approve': 'A',
    'purchase.request.cancel': 'A',
    'purchase.record.read': 'A',
    'purchase.price_history.read': 'A',
    'vendor.vendor.read': 'A',
    'workforce.employee.read': 'A',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'A',
    'workforce.attendance.edit': 'A',
    'workforce.break.log_self': 'S',
    'workforce.shift.create': 'A',
    'workforce.shift.read': 'A',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'A',
    'workforce.leave.decide': 'A',
    'workforce.performance.read': 'A',
    'task.task.create': 'A',
    'task.task.read': 'A',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.task.verify': 'A',
    'task.task.cancel': 'A',
    'task.template.manage': 'A',
    'task.recurrence.manage': 'A',
    'task.comment.create': 'S',
    'sales.entry.read': 'A',
    'analytics.dashboard.read': 'A',
    'analytics.sales.read': 'A',
    'analytics.consumption.read': 'A',
    'analytics.performance.read': 'A',
    'analytics.waste.read': 'A',
    'analytics.export.create': 'A',
    'messaging.direct.send': 'A',
    'messaging.broadcast.send': 'A',
    'messaging.message.read': 'A',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
    'crm.customer.read': 'A',
    'crm.game.configure': 'A',
    'crm.reward.define': 'A',
    'crm.reward.issue': 'A',
    'crm.reward.redeem': 'A',
    'crm.analytics.read': 'A',
  },
  STORE_MANAGER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'auth.password.reset_other': 'O',
    'admin.user.read': 'O',
    'inventory.item.read': 'O',
    'inventory.stock.read': 'O',
    'inventory.transaction.create': 'O',
    'inventory.transaction.read': 'O',
    'inventory.wastage.create': 'O',
    'inventory.adjustment.create': 'O',
    'purchase.request.create': 'O',
    'purchase.request.read': 'O',
    'purchase.request.cancel': 'O',
    'purchase.record.read': 'O',
    'workforce.employee.read': 'O',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'O',
    'workforce.attendance.edit': 'O',
    'workforce.break.log_self': 'S',
    'workforce.shift.create': 'O',
    'workforce.shift.read': 'O',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'O',
    'workforce.leave.decide': 'O',
    'workforce.performance.read': 'O',
    'task.task.create': 'O',
    'task.task.read': 'O',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.task.verify': 'O',
    'task.task.cancel': 'O',
    'task.comment.create': 'S',
    'sales.entry.create': 'O',
    'sales.entry.read': 'O',
    'sales.entry.amend': 'O',
    'analytics.dashboard.read': 'O',
    'analytics.sales.read': 'O',
    'analytics.consumption.read': 'O',
    'analytics.performance.read': 'O',
    'analytics.waste.read': 'O',
    'messaging.direct.send': 'O',
    'messaging.broadcast.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
    'crm.customer.read': 'O',
    'crm.reward.redeem': 'O',
    'crm.analytics.read': 'O',
  },
  KITCHEN_MANAGER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'inventory.item.read': 'O',
    'inventory.stock.read': 'O',
    'inventory.transaction.create': 'O',
    'inventory.transaction.read': 'O',
    'inventory.wastage.create': 'O',
    'purchase.request.create': 'O',
    'purchase.request.read': 'O',
    'purchase.request.cancel': 'O',
    'workforce.employee.read': 'O',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'O',
    'workforce.break.log_self': 'S',
    'workforce.shift.create': 'O',
    'workforce.shift.read': 'O',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'O',
    'workforce.performance.read': 'O',
    'task.task.create': 'O',
    'task.task.read': 'O',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.task.verify': 'O',
    'task.task.cancel': 'O',
    'task.comment.create': 'S',
    'analytics.dashboard.read': 'O',
    'analytics.consumption.read': 'O',
    'analytics.performance.read': 'O',
    'analytics.waste.read': 'O',
    'messaging.direct.send': 'O',
    'messaging.broadcast.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
  },
  INVENTORY_MANAGER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'inventory.item.create': 'A',
    'inventory.item.read': 'A',
    'inventory.item.update': 'A',
    'inventory.item.deactivate': 'A',
    'inventory.category.manage': 'A',
    'inventory.unit.manage': 'A',
    'inventory.stock.read': 'A',
    'inventory.transaction.create': 'A',
    'inventory.transaction.read': 'A',
    'inventory.wastage.create': 'A',
    'inventory.adjustment.create': 'A',
    'inventory.transfer.create': 'A',
    'inventory.reorder_level.update': 'A',
    'purchase.request.create': 'A',
    'purchase.request.read': 'A',
    'purchase.record.read': 'A',
    'purchase.price_history.read': 'A',
    'vendor.vendor.read': 'A',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'S',
    'workforce.break.log_self': 'S',
    'workforce.shift.read': 'S',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'S',
    'task.task.read': 'S',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.comment.create': 'S',
    'analytics.dashboard.read': 'A',
    'analytics.consumption.read': 'A',
    'analytics.waste.read': 'A',
    'messaging.direct.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
  },
  PURCHASE_MANAGER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'inventory.item.read': 'A',
    'inventory.stock.read': 'A',
    'purchase.request.read': 'A',
    'purchase.request.approve': 'A',
    'purchase.request.cancel': 'A',
    'purchase.record.create': 'A',
    'purchase.record.read': 'A',
    'purchase.record.void': 'A',
    'purchase.price_history.read': 'A',
    'vendor.vendor.create': 'A',
    'vendor.vendor.read': 'A',
    'vendor.vendor.update': 'A',
    'vendor.vendor.deactivate': 'A',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'S',
    'workforce.break.log_self': 'S',
    'workforce.shift.read': 'S',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'S',
    'task.task.read': 'S',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.comment.create': 'S',
    'analytics.dashboard.read': 'A',
    'messaging.direct.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
  },
  HR_ACCOUNTS: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'auth.password.reset_other': 'A',
    'admin.user.create': 'A',
    'admin.user.read': 'A',
    'admin.user.update': 'A',
    'admin.user.disable': 'A',
    'workforce.employee.create': 'A',
    'workforce.employee.read': 'A',
    'workforce.employee.update': 'A',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'A',
    'workforce.attendance.edit': 'A',
    'workforce.break.log_self': 'S',
    'workforce.shift.read': 'A',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'A',
    'workforce.leave.decide': 'A',
    'workforce.salary.read': 'A',
    'workforce.salary.write': 'A',
    'workforce.performance.read': 'A',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.comment.create': 'S',
    'sales.entry.read': 'A',
    'analytics.dashboard.read': 'A',
    'analytics.sales.read': 'A',
    'analytics.performance.read': 'A',
    'analytics.export.create': 'A',
    'messaging.direct.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
  },
  KITCHEN_STAFF: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'S',
    'workforce.break.log_self': 'S',
    'workforce.shift.read': 'S',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'S',
    'task.task.read': 'S',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.comment.create': 'S',
    'messaging.direct.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
  },
  COUNTER_CASHIER: {
    'auth.session.create': 'A',
    'auth.password.change': 'S',
    'workforce.attendance.punch_self': 'S',
    'workforce.attendance.read': 'S',
    'workforce.break.log_self': 'S',
    'workforce.shift.read': 'S',
    'workforce.leave.request': 'S',
    'workforce.leave.read': 'S',
    'task.task.read': 'S',
    'task.task.update_self': 'S',
    'task.task.complete': 'S',
    'task.comment.create': 'S',
    'sales.entry.create': 'O',
    'sales.entry.read': 'O',
    'messaging.direct.send': 'O',
    'messaging.message.read': 'O',
    'notification.own.read': 'S',
    'notification.preference.update': 'S',
    'crm.reward.redeem': 'O',
  },
};
